// screw-up - Easy package metadata inserter on Vite plugin
// Copyright (c) Kouji Matsui (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/screw-up/

import { existsSync } from 'fs';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { basename, dirname, join } from 'path';
import { Logger } from './internal';
import { PackageMetadata } from './types';

/**
 * Convert string key to valid TypeScript identifier
 * @param key - The key to convert
 * @returns Valid TypeScript identifier
 */
const sanitizeKey = (key: string): string => {
  // Replace dots and other invalid characters with underscores
  return key.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1');
};

/**
 * Generate TypeScript metadata file content from package metadata
 * @param metadata - Package metadata
 * @param outputKeys - Array of keys to output
 * @returns TypeScript file content
 */
export const generateMetadataFileContent = (
  metadata: PackageMetadata,
  outputKeys: readonly string[]
): string => {
  const lines: string[] = [];

  lines.push('// @ts-nocheck');
  lines.push('// This file is auto-generated by screw-up plugin');
  lines.push('// Do not edit manually');
  lines.push('');

  for (const key of outputKeys) {
    const value = metadata[key];
    if (value) {
      const sanitizedKey = sanitizeKey(key);
      const escapedValue = JSON.stringify(value);
      lines.push(`export const ${sanitizedKey} = ${escapedValue};`);
    }
  }

  lines.push('');

  return lines.join('\n');
};

export const writeFileIfChanged = async (
  filePath: string,
  content: string,
  description: string,
  logger: Logger
): Promise<boolean> => {
  try {
    // Check if file exists and compare content
    let shouldWrite = !existsSync(filePath);
    if (!shouldWrite) {
      try {
        const existingContent = await readFile(filePath, 'utf-8');
        shouldWrite = existingContent !== content;
      } catch {
        // File doesn't exist or couldn't read, we should write it
        shouldWrite = true;
      }
    }

    if (shouldWrite) {
      // Ensure directory exists
      await mkdir(dirname(filePath), { recursive: true });
      // Write file only if content has changed
      await writeFile(filePath, content);
      return true;
    } else {
      // File content is the same, no need to write
      return false;
    }
  } catch (error) {
    logger.warn(`Failed to write ${description}: ${filePath}: ${error}`);
    return false;
  }
};

export const ensureMetadataGitignore = async (
  metadataSourcePath: string,
  logger: Logger
): Promise<boolean> => {
  const metadataDirectory = dirname(metadataSourcePath);
  const gitignorePath = join(metadataDirectory, '.gitignore');

  if (existsSync(gitignorePath)) {
    return false;
  }

  try {
    await mkdir(metadataDirectory, { recursive: true });
    const metadataFileName = basename(metadataSourcePath);
    const gitignoreContent = `# Auto-generated by screw-up plugin\n${metadataFileName}\n`;
    await writeFile(gitignorePath, gitignoreContent);
    return true;
  } catch (error) {
    logger.warn(
      `Failed to write .gitignore for metadata source: ${gitignorePath}: ${error}`
    );
    return false;
  }
};
